// Outlet database: ownership, funding, leaning and a baseline reliability estimate.
// `reliability` (0-100) is an editorial starting point, not ground truth — the app blends
// it with a live corroboration rate measured from the feeds. Edit freely.
// `group` = ultimate owner; outlets sharing a group count as ONE voice in cross-verification.
// `wiki` = Wikipedia article used to pull the live profile and controversies section.

const SOURCES = [
  { id: 'bbc', name: 'BBC News', domain: 'bbc.co.uk', alt: ['bbc.com'], country: 'UK', type: 'public broadcaster',
    owner: 'British Broadcasting Corporation', group: 'BBC', funding: 'UK licence fee (public)', leaning: 'center', reliability: 85,
    independent: false, wiki: 'BBC News',
    notes: ['Bound by Royal Charter impartiality rules; regularly accused of bias by both left and right.'],
    feeds: [{ url: 'https://feeds.bbci.co.uk/news/world/rss.xml', topics: ['world'] },
            { url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', topics: ['tech'] },
            { url: 'https://feeds.bbci.co.uk/news/business/rss.xml', topics: ['business'] }] },
  { id: 'aljazeera', name: 'Al Jazeera', domain: 'aljazeera.com', country: 'Qatar', type: 'state-funded broadcaster',
    owner: 'Al Jazeera Media Network', group: 'Al Jazeera', funding: 'Government of Qatar', leaning: 'center-left', reliability: 72,
    independent: false, wiki: 'Al Jazeera',
    notes: ['Funded by the Qatari state; critics say coverage aligns with Qatar\'s foreign policy.', 'Has been banned or restricted in several countries.'],
    feeds: [{ url: 'https://www.aljazeera.com/xml/rss/all.xml', topics: ['world'] }] },
  { id: 'guardian', name: 'The Guardian', domain: 'theguardian.com', country: 'UK', type: 'newspaper',
    owner: 'Guardian Media Group (Scott Trust)', group: 'Scott Trust', funding: 'Trust-owned; reader contributions & ads', leaning: 'center-left', reliability: 80,
    independent: true, wiki: 'The Guardian',
    notes: ['Owned by a trust designed to protect editorial independence; openly progressive opinion pages.'],
    feeds: [{ url: 'https://www.theguardian.com/world/rss', topics: ['world'] },
            { url: 'https://www.theguardian.com/environment/climate-crisis/rss', topics: ['climate'] }] },
  { id: 'npr', name: 'NPR', domain: 'npr.org', country: 'US', type: 'public radio',
    owner: 'National Public Radio, Inc. (nonprofit)', group: 'NPR', funding: 'Member stations, sponsors, donors; historically some federal funds via CPB', leaning: 'center-left', reliability: 82,
    independent: false, wiki: 'NPR',
    notes: ['Frequently criticised by US conservatives for perceived liberal bias.'],
    feeds: [{ url: 'https://feeds.npr.org/1004/rss.xml', topics: ['world'] },
            { url: 'https://feeds.npr.org/1014/rss.xml', topics: ['politics'] }] },
  { id: 'dw', name: 'Deutsche Welle', domain: 'dw.com', country: 'Germany', type: 'public broadcaster',
    owner: 'Deutsche Welle (public)', group: 'Deutsche Welle', funding: 'German federal tax budget', leaning: 'center', reliability: 84,
    independent: false, wiki: 'Deutsche Welle', notes: ['Germany\'s state-funded international broadcaster; editorially independent by law.'],
    feeds: [{ url: 'https://rss.dw.com/rdf/rss-en-all', topics: ['world'] }] },
  { id: 'france24', name: 'France 24', domain: 'france24.com', country: 'France', type: 'public broadcaster',
    owner: 'France Médias Monde (state-owned)', group: 'France Médias Monde', funding: 'French state', leaning: 'center', reliability: 80,
    independent: false, wiki: 'France 24', notes: ['French state-owned international news channel.'],
    feeds: [{ url: 'https://www.france24.com/en/rss', topics: ['world'] }] },
  { id: 'sky', name: 'Sky News', domain: 'news.sky.com', alt: ['sky.com'], country: 'UK', type: 'broadcaster',
    owner: 'Sky Group (Comcast)', group: 'Comcast', funding: 'Commercial', leaning: 'center', reliability: 80,
    independent: false, wiki: 'Sky News', notes: ['Regulated by Ofcom impartiality rules.'],
    feeds: [{ url: 'https://feeds.skynews.com/feeds/rss/world.xml', topics: ['world'] }] },
  { id: 'independent', name: 'The Independent', domain: 'independent.co.uk', country: 'UK', type: 'digital newspaper',
    owner: 'Independent Digital News & Media', group: 'Lebedev / Abuljadayel', funding: 'Commercial', leaning: 'center-left', reliability: 72,
    independent: false, wiki: 'The Independent',
    notes: ['Owned by Evgeny Lebedev with a minority stake held by Saudi investor Sultan Muhammad Abuljadayel, which drew scrutiny.'],
    feeds: [{ url: 'https://www.independent.co.uk/news/world/rss', topics: ['world'] }] },
  { id: 'euronews', name: 'Euronews', domain: 'euronews.com', country: 'EU', type: 'broadcaster',
    owner: 'Alpac Capital', group: 'Alpac Capital', funding: 'Commercial; some EU contracts', leaning: 'center', reliability: 72,
    independent: false, wiki: 'Euronews',
    notes: ['Majority owner Alpac Capital has been reported to have links to allies of Hungarian PM Viktor Orbán.'],
    feeds: [{ url: 'https://www.euronews.com/rss?level=theme&name=news', topics: ['world'] }] },
  { id: 'nyt', name: 'The New York Times', domain: 'nytimes.com', country: 'US', type: 'newspaper',
    owner: 'The New York Times Company', group: 'NYT Co.', funding: 'Subscriptions & ads (public company, Ochs-Sulzberger family control)', leaning: 'center-left', reliability: 82,
    independent: false, wiki: 'The New York Times', notes: ['Newspaper of record; criticised from both sides on specific coverage decisions.'],
    feeds: [{ url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', topics: ['world'] },
            { url: 'https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml', topics: ['politics'] }] },
  { id: 'wapo', name: 'The Washington Post', domain: 'washingtonpost.com', country: 'US', type: 'newspaper',
    owner: 'Nash Holdings (Jeff Bezos)', group: 'Bezos', funding: 'Subscriptions & ads', leaning: 'center-left', reliability: 80,
    independent: false, wiki: 'The Washington Post', notes: ['Owner influence over the opinion section has been publicly debated.'],
    feeds: [{ url: 'https://feeds.washingtonpost.com/rss/world', topics: ['world'] }] },
  { id: 'wsj', name: 'The Wall Street Journal', domain: 'wsj.com', country: 'US', type: 'newspaper',
    owner: 'Dow Jones (News Corp)', group: 'Murdoch', funding: 'Subscriptions & ads', leaning: 'center-right', reliability: 82,
    independent: false, wiki: 'The Wall Street Journal', notes: ['News desk rated highly; opinion pages are conservative.'],
    feeds: [{ url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', topics: ['world', 'business'] }] },
  { id: 'fox', name: 'Fox News', domain: 'foxnews.com', country: 'US', type: 'cable news',
    owner: 'Fox Corporation', group: 'Murdoch', funding: 'Commercial', leaning: 'right', reliability: 55,
    independent: false, wiki: 'Fox News',
    notes: ['Paid $787.5M in 2023 to settle Dominion Voting Systems defamation suit over 2020 election claims.'],
    feeds: [{ url: 'https://moxie.foxnews.com/google-publisher/world.xml', topics: ['world'] },
            { url: 'https://moxie.foxnews.com/google-publisher/politics.xml', topics: ['politics'] }] },
  { id: 'cbs', name: 'CBS News', domain: 'cbsnews.com', country: 'US', type: 'broadcaster',
    owner: 'Paramount Skydance', group: 'Paramount Skydance', funding: 'Commercial', leaning: 'center-left', reliability: 78,
    independent: false, wiki: 'CBS News', notes: ['Ownership change in 2025 prompted debate over editorial independence.'],
    feeds: [{ url: 'https://www.cbsnews.com/latest/rss/world', topics: ['world'] }] },
  { id: 'abc', name: 'ABC News (US)', domain: 'abcnews.go.com', alt: ['abcnews.com'], country: 'US', type: 'broadcaster',
    owner: 'The Walt Disney Company', group: 'Disney', funding: 'Commercial', leaning: 'center-left', reliability: 78,
    independent: false, wiki: 'ABC News (United States)', notes: [],
    feeds: [{ url: 'https://abcnews.go.com/abcnews/internationalheadlines', topics: ['world'] }] },
  { id: 'cnbc', name: 'CNBC', domain: 'cnbc.com', country: 'US', type: 'business broadcaster',
    owner: 'Comcast cable-network group', group: 'Comcast', funding: 'Commercial', leaning: 'center', reliability: 78,
    independent: false, wiki: 'CNBC', notes: [],
    feeds: [{ url: 'https://www.cnbc.com/id/100727362/device/rss/rss.html', topics: ['world', 'business'] }] },
  { id: 'rt', name: 'RT', domain: 'rt.com', country: 'Russia', type: 'state media',
    owner: 'TV-Novosti (Russian state)', group: 'Russian state', funding: 'Russian federal budget', leaning: 'state-aligned', reliability: 20,
    independent: false, wiki: 'RT (TV network)',
    notes: ['Russian state-controlled; banned in the EU since 2022 and widely documented as a state propaganda outlet.', 'Included deliberately so you can see how state narratives diverge from consensus.'],
    feeds: [{ url: 'https://www.rt.com/rss/news/', topics: ['world'] }] },
  { id: 'scmp', name: 'South China Morning Post', domain: 'scmp.com', country: 'Hong Kong', type: 'newspaper',
    owner: 'Alibaba Group', group: 'Alibaba', funding: 'Commercial', leaning: 'center', reliability: 70,
    independent: false, wiki: 'South China Morning Post', notes: ['Concerns about Beijing-friendly editorial drift since the 2016 Alibaba acquisition.'],
    feeds: [{ url: 'https://www.scmp.com/rss/91/feed', topics: ['world'] }] },
  { id: 'thehindu', name: 'The Hindu', domain: 'thehindu.com', country: 'India', type: 'newspaper',
    owner: 'The Hindu Group (Kasturi & Sons)', group: 'Kasturi & Sons', funding: 'Commercial', leaning: 'center-left', reliability: 78,
    independent: false, wiki: 'The Hindu', notes: [],
    feeds: [{ url: 'https://www.thehindu.com/news/national/feeder/default.rss', topics: ['india'] },
            { url: 'https://www.thehindu.com/news/international/feeder/default.rss', topics: ['world'] }] },
  { id: 'indianexpress', name: 'The Indian Express', domain: 'indianexpress.com', country: 'India', type: 'newspaper',
    owner: 'Indian Express Group', group: 'Indian Express Group', funding: 'Commercial', leaning: 'center', reliability: 77,
    independent: false, wiki: 'The Indian Express', notes: ['Known for investigative work (e.g. Panama/Pandora Papers partner).'],
    feeds: [{ url: 'https://indianexpress.com/section/india/feed/', topics: ['india'] }] },
  { id: 'ndtv', name: 'NDTV', domain: 'ndtv.com', country: 'India', type: 'broadcaster',
    owner: 'Adani Group (controlling stake since 2022)', group: 'Adani', funding: 'Commercial', leaning: 'center', reliability: 68,
    independent: false, wiki: 'NDTV', notes: ['The 2022 Adani takeover and founders\' exit raised editorial-independence concerns.'],
    feeds: [{ url: 'https://feeds.feedburner.com/ndtvnews-top-stories', topics: ['india'] }] },
  { id: 'toi', name: 'Times of India', domain: 'timesofindia.indiatimes.com', alt: ['indiatimes.com'], country: 'India', type: 'newspaper',
    owner: 'Bennett, Coleman & Co. (Times Group)', group: 'Times Group', funding: 'Commercial', leaning: 'center-right', reliability: 62,
    independent: false, wiki: 'The Times of India',
    notes: ['Times Group executives featured in the 2018 Cobrapost "Operation 136" paid-news sting.'],
    feeds: [{ url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms', topics: ['india'] }] },
  { id: 'ht', name: 'Hindustan Times', domain: 'hindustantimes.com', country: 'India', type: 'newspaper',
    owner: 'HT Media (K. K. Birla family)', group: 'HT Media', funding: 'Commercial', leaning: 'center', reliability: 70,
    independent: false, wiki: 'Hindustan Times', notes: [],
    feeds: [{ url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml', topics: ['india'] },
            { url: 'https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml', topics: ['world'] }] },
  { id: 'scroll', name: 'Scroll.in', domain: 'scroll.in', country: 'India', type: 'independent digital',
    owner: 'Scroll Media', group: 'Scroll Media', funding: 'Reader memberships, ads, investors', leaning: 'center-left', reliability: 72,
    independent: true, wiki: 'Scroll.in', notes: [],
    feeds: [{ url: 'https://feeds.feedburner.com/ScrollinArticles.rss', topics: ['india'] }] },
  { id: 'thewire', name: 'The Wire', domain: 'thewire.in', country: 'India', type: 'independent nonprofit',
    owner: 'Foundation for Independent Journalism', group: 'FIJ', funding: 'Reader donations & grants', leaning: 'left', reliability: 66,
    independent: true, wiki: 'The Wire (India)', notes: ['Retracted its 2022 series on Meta/Instagram after its sourcing was found to be fabricated.'],
    feeds: [{ url: 'https://thewire.in/rss', topics: ['india'] }] },
  { id: 'propublica', name: 'ProPublica', domain: 'propublica.org', country: 'US', type: 'independent nonprofit',
    owner: 'ProPublica (nonprofit)', group: 'ProPublica', funding: 'Philanthropy & donors', leaning: 'center-left', reliability: 88,
    independent: true, wiki: 'ProPublica', notes: ['Multiple Pulitzer Prizes for investigative reporting.'],
    feeds: [{ url: 'https://www.propublica.org/feeds/propublica/main', topics: ['politics'] }] },
  { id: 'intercept', name: 'The Intercept', domain: 'theintercept.com', country: 'US', type: 'independent nonprofit',
    owner: 'The Intercept (nonprofit, founded by First Look Media)', group: 'The Intercept', funding: 'Donors', leaning: 'left', reliability: 68,
    independent: true, wiki: 'The Intercept', notes: ['Adversarial investigative outlet; has had high-profile source-protection failures.'],
    feeds: [{ url: 'https://theintercept.com/feed/?lang=en', topics: ['politics'] }] },
  { id: 'democracynow', name: 'Democracy Now!', domain: 'democracynow.org', country: 'US', type: 'independent nonprofit',
    owner: 'Democracy Now! Productions', group: 'Democracy Now!', funding: 'Viewers, listeners, foundations (no ads)', leaning: 'left', reliability: 65,
    independent: true, wiki: 'Democracy Now!', notes: [],
    feeds: [{ url: 'https://www.democracynow.org/democracynow.rss', topics: ['politics', 'world'] }] },
  { id: 'ars', name: 'Ars Technica', domain: 'arstechnica.com', country: 'US', type: 'tech publication',
    owner: 'Condé Nast (Advance Publications)', group: 'Advance', funding: 'Commercial', leaning: 'center-left', reliability: 82,
    independent: false, wiki: 'Ars Technica', notes: [],
    feeds: [{ url: 'https://feeds.arstechnica.com/arstechnica/index', topics: ['tech', 'science'] }] },
  { id: 'verge', name: 'The Verge', domain: 'theverge.com', country: 'US', type: 'tech publication',
    owner: 'Vox Media', group: 'Vox Media', funding: 'Commercial', leaning: 'center-left', reliability: 76,
    independent: false, wiki: 'The Verge', notes: [],
    feeds: [{ url: 'https://www.theverge.com/rss/index.xml', topics: ['tech'] }] },
  { id: 'nature', name: 'Nature', domain: 'nature.com', country: 'UK', type: 'scientific journal',
    owner: 'Springer Nature', group: 'Springer Nature', funding: 'Subscriptions / APCs', leaning: 'center', reliability: 92,
    independent: false, wiki: 'Nature (journal)', notes: [],
    feeds: [{ url: 'https://www.nature.com/nature.rss', topics: ['science'] }] },
  { id: 'sciencedaily', name: 'ScienceDaily', domain: 'sciencedaily.com', country: 'US', type: 'press-release aggregator',
    owner: 'ScienceDaily LLC', group: 'ScienceDaily', funding: 'Ads', leaning: 'center', reliability: 70,
    independent: true, wiki: 'ScienceDaily', notes: ['Republishes institutional press releases; not independently reported.'],
    feeds: [{ url: 'https://www.sciencedaily.com/rss/top/science.xml', topics: ['science', 'health'] }] },
  { id: 'espn', name: 'ESPN', domain: 'espn.com', country: 'US', type: 'sports',
    owner: 'The Walt Disney Company', group: 'Disney', funding: 'Commercial', leaning: 'center', reliability: 75,
    independent: false, wiki: 'ESPN', notes: [],
    feeds: [{ url: 'https://www.espn.com/espn/rss/news', topics: ['sports'] }] },
  // Outlets without usable public feeds. They still arrive via Google News, GDELT and Wikipedia
  // citations (common in time travel), so they get proper ratings instead of "unrated".
  { id: 'reuters', name: 'Reuters', domain: 'reuters.com', country: 'UK', type: 'news agency',
    owner: 'Thomson Reuters', group: 'Thomson Reuters', funding: 'Commercial (wire service)', leaning: 'center', reliability: 88,
    independent: false, wiki: 'Reuters', notes: ['Wire agency: many outlets republish its copy, which can make one report look like many.'], feeds: [] },
  { id: 'ap', name: 'Associated Press', domain: 'apnews.com', alt: ['ap.org'], country: 'US', type: 'news agency',
    owner: 'Associated Press (nonprofit cooperative)', group: 'AP', funding: 'Member news organisations & licensing', leaning: 'center', reliability: 88,
    independent: true, wiki: 'Associated Press', notes: ['Wire agency: many outlets republish its copy, which can make one report look like many.'], feeds: [] },
  { id: 'cnn', name: 'CNN', domain: 'cnn.com', country: 'US', type: 'cable news',
    owner: 'Warner Bros. Discovery', group: 'Warner Bros. Discovery', funding: 'Commercial', leaning: 'center-left', reliability: 72,
    independent: false, wiki: 'CNN', notes: [], feeds: [] },
  { id: 'cbc', name: 'CBC News', domain: 'cbc.ca', country: 'Canada', type: 'public broadcaster',
    owner: 'Canadian Broadcasting Corporation (Crown corporation)', group: 'CBC', funding: 'Canadian federal funding & ads', leaning: 'center', reliability: 80,
    independent: false, wiki: 'CBC News', notes: [], feeds: [] },
  { id: 'pbs', name: 'PBS', domain: 'pbs.org', country: 'US', type: 'public broadcaster',
    owner: 'Public Broadcasting Service (nonprofit)', group: 'PBS', funding: 'Member stations, donors; historically some federal funds via CPB', leaning: 'center', reliability: 82,
    independent: false, wiki: 'PBS NewsHour', notes: [], feeds: [] },
  { id: 'axios', name: 'Axios', domain: 'axios.com', country: 'US', type: 'digital news',
    owner: 'Cox Enterprises', group: 'Cox Enterprises', funding: 'Commercial', leaning: 'center', reliability: 78,
    independent: false, wiki: 'Axios (website)', notes: [], feeds: [] },
  { id: 'politico', name: 'Politico', domain: 'politico.com', alt: ['politico.eu'], country: 'US', type: 'political news',
    owner: 'Axel Springer SE', group: 'Axel Springer', funding: 'Commercial', leaning: 'center-left', reliability: 76,
    independent: false, wiki: 'Politico', notes: [], feeds: [] },
  { id: 'bloomberg', name: 'Bloomberg', domain: 'bloomberg.com', country: 'US', type: 'business news',
    owner: 'Bloomberg L.P. (Michael Bloomberg)', group: 'Bloomberg L.P.', funding: 'Terminal subscriptions & ads', leaning: 'center', reliability: 82,
    independent: false, wiki: 'Bloomberg News', notes: [], feeds: [] },
  // Fact-checkers: their presence in a story cluster flags the story as checked / contested.
  { id: 'altnews', name: 'Alt News', domain: 'altnews.in', country: 'India', type: 'fact-checker', factChecker: true,
    owner: 'Pravda Media Foundation', group: 'Pravda Media Foundation', funding: 'Donations', leaning: 'center-left', reliability: 80,
    independent: true, wiki: 'Alt News', notes: ['IFCN signatory. Co-founder Mohammed Zubair was arrested in 2022, drawing press-freedom criticism.'],
    feeds: [{ url: 'https://www.altnews.in/feed/', topics: ['india', 'factcheck'] }] },
  { id: 'snopes', name: 'Snopes', domain: 'snopes.com', country: 'US', type: 'fact-checker', factChecker: true,
    owner: 'Snopes Media Group', group: 'Snopes', funding: 'Ads & memberships', leaning: 'center', reliability: 78,
    independent: true, wiki: 'Snopes', notes: ['In 2021 retracted ~60 articles after a co-founder was found to have plagiarised.'],
    feeds: [{ url: 'https://www.snopes.com/feed/', topics: ['factcheck'] }] },
  { id: 'fullfact', name: 'Full Fact', domain: 'fullfact.org', country: 'UK', type: 'fact-checker', factChecker: true,
    owner: 'Full Fact (charity)', group: 'Full Fact', funding: 'Charitable donations & grants', leaning: 'center', reliability: 86,
    independent: true, wiki: 'Full Fact', notes: [],
    feeds: [{ url: 'https://fullfact.org/feed/', topics: ['factcheck'] }] },
  { id: 'politifact', name: 'PolitiFact', domain: 'politifact.com', country: 'US', type: 'fact-checker', factChecker: true,
    owner: 'Poynter Institute', group: 'Poynter', funding: 'Nonprofit', leaning: 'center', reliability: 82,
    independent: true, wiki: 'PolitiFact', notes: ['Conservatives have alleged its ratings skew against Republicans.'],
    feeds: [{ url: 'https://www.politifact.com/rss/all/', topics: ['factcheck', 'politics'] }] },
];

// Aggregator feeds: each item names its real publisher, which we map back to an outlet.
const AGGREGATORS = [
  { url: 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', topics: ['world'], via: 'Google News (US)' },
  { url: 'https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en', topics: ['india'], via: 'Google News (IN)' },
];

const byId = new Map(SOURCES.map(s => [s.id, s]));
const byDomain = new Map();
for (const s of SOURCES) for (const d of [s.domain, ...(s.alt || [])]) byDomain.set(d, s);

function hostOf(url) {
  try { return new URL(url).hostname.replace(/^www\./, ''); } catch { return ''; }
}

// Find a known outlet for a URL/hostname, or synthesise an "unrated" one.
const adHoc = new Map();
function resolveSource(urlOrHost, displayName) {
  const host = urlOrHost.includes('/') ? hostOf(urlOrHost) : urlOrHost.replace(/^www\./, '');
  for (let h = host; h.includes('.'); h = h.slice(h.indexOf('.') + 1)) {
    if (byDomain.has(h)) return byDomain.get(h);
  }
  if (!host) return null;
  if (!adHoc.has(host)) {
    adHoc.set(host, {
      id: 'x:' + host, name: displayName || host, domain: host, country: '?', type: 'unrated outlet',
      owner: 'Unknown', group: host, funding: 'Unknown', leaning: 'unknown', reliability: null,
      independent: null, wiki: displayName || null, notes: ['Not in the curated outlet database — treat with extra caution.'], feeds: [],
      unrated: true,
    });
  }
  return adHoc.get(host);
}

function getSource(id) { return byId.get(id) || [...adHoc.values()].find(s => s.id === id) || null; }
function allSources() { return [...SOURCES, ...adHoc.values()]; }

module.exports = { SOURCES, AGGREGATORS, resolveSource, getSource, allSources, hostOf };
